[workspace]
members = ["elb-log-parser"]
resolver = "3"

[workspace.package]
authors = ["Jihyeon Kim <simnalamburt@gmail.com>"]
edition = "2024"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/simnalamburt/sample-rust-apps"
